site_name: 通达信公式
site_url: https://tdx.icopy.site/
theme:
  font: false
  name: material
  palette:
    primary: black
    accent: white
  language: zh
  features:
    - navigation.top
plugins:
  - search:
      prebuild_index: true
      lang: ja
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences
  - admonition
  - toc:
      toc_depth: 6
      permalink: true

extra_javascript:
  - https://cdn.staticfile.org/highlight.js/11.0.0-alpha1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdn.staticfile.org/highlight.js/11.0.0-alpha1/styles/default.min.css
  - https://cdn.staticfile.org/highlight.js/11.0.0-alpha1/styles/vs.min.css

nav:
    - 基础教程: "index.md"
    - 教程:
      - 初级教程: "教程/基础教程.md"
      - 高级教程: "教程/高级教程.md"
      - 答疑: "教程/答疑.md"
    - 代码示例:
        - 技术指标公式: "代码示例/技术指标公式.md"
        - 条件选股公式: "代码示例/条件选股公式.md"
        - 五彩k线指标: "代码示例/五彩k线指标.md"
        - 专家系统: "代码示例/专家系统.md"
    - 函数:
        - 引用函数: "函数/引用函数.md"
        - 操作符: "函数/操作符.md"
        - 绘图函数: "函数/绘图函数.md"
        - 线型和资源: "函数/线型和资源.md"
        - 数学函数: "函数/数学函数.md"
        - 时间函数: "函数/时间函数.md"
        - 统计函数: "函数/统计函数.md"
        - 财务函数: "函数/财务函数.md"
        - 资金流向函数: "函数/资金流向函数.md"
        - 选择函数: "函数/选择函数.md"
        - 逻辑函数: "函数/逻辑函数.md"
        - 及时行情函数: "函数/及时行情函数.md"
        - 序列行情函数: "函数/序列行情函数.md"
        - 账户函数: "函数/账户函数.md"
        - 板块字符函数: "函数/板块字符函数.md"
        - 形态函数: "函数/形态函数.md"
        - 指数函数: "函数/指数函数.md"
        - 交易信号函数: "函数/交易信号函数.md"
        - 其他函数: "函数/其他函数.md"
